### ISSUE TITLE
路由同步失败

### ISSUE THREAD

**Issue by petteran** [typefo/pbx-mon#10]
路由表 gfgg 同步失败！ 请问这个怎么解决？
写数据到 freeswitch 失败嘛？

**Comment by typefo** [comment]
需要贴出后台具体的错误日志，有可能是你的 freeswitch 目录权限不正确

**Comment by petteran** [comment]
是的,conf目录给了777权限就好了

**Comment by petteran** [comment]
是的,conf目录给了777权限就好了

**Comment by petteran** [comment]
接入了之后出现了很多Service Unavailable(503),这个是怎么回事? 我对freeswitch 不是很熟悉

**Comment by petteran** [comment]
已经处理了,不是平台问题.
