### ISSUE TITLE
CDR and report do not display data

### ISSUE THREAD

**Issue by zhq1** [typefo/pbx-mon#2]
At present, it has been deployed. There is no problem with the phone and recording during the test, but the CDR and report do not display the data. What's the matter, thank you!

**Comment by typefo** [comment]
看错误提示，貌似你没有安装 redis 和 mysql，pbxmon安装脚本并不包含他们的安装

**Comment by zhq1** [comment]
也就是说除了安装MariaDB 5.5和phpredis 3.1.2，还需要安装MySQL和Redis吗？

**Comment by typefo** [comment]
如果确认redis和mysql都已安装，可能还需要修改 /var/www/conf/application.ini 配置文件

**Comment by zhq1** [comment]
[root@vultr ~]# ps aux | grep mysql
mysql      827  0.0  0.0 113308  1608 ?        Ss   09:04   0:00 /bin/sh /usr/bin/mysqld_safe --basedir=/usr
mysql     1149  0.0  2.3 978508 92972 ?        Sl   09:04   0:07 /usr/libexec/mysqld --basedir=/usr --datadir=/var/lib/mysql --plugin-dir=/usr/lib64/mysql/plugin --log-error=/var/log/mariadb/mariadb.log --pid-file=/var/run/mariadb/mariadb.pid --socket=/var/lib/mysql/mysql.sock --port=3306
root     12748  0.0  0.0 112712   980 pts/1    S+   12:15   0:00 grep --color=auto mysql

[root@vultr ~]# ps aux | grep redis
redis      716  0.0  0.1 142956  5872 ?        Ssl  09:04   0:10 /usr/bin/redis-server 127.0.0.1:6379
root     12830  0.0  0.0 112712   976 pts/1    S+   12:15   0:00 grep --color=auto redis

**Comment by typefo** [comment]
还有需要修改 /var/cdr/config.php 文件以设置 redis 和 mysql 的密码，默认的配置是不正确的。。

**Comment by typefo** [comment]
你可能需要检查 php 的日志，确认 freeswitch 有将 cdr 数据送上来

**Comment by zhq1** [comment]
确实没有找到到底什么原因，PHP、nginx、redis、mariadb都是正常的访问日志，未报异常

**Comment by zhq1** [comment]
编译安装 FreeSWITCH

$ wget http://files.freeswitch.org/freeswitch-releases/freeswitch-1.6.15.tar.gz
$ tar -xzvf freeswitch-1.6.15.tar.gz
$ cd freeswitch-1.6.15
$ ./configure --disable-debug --disable-libyuv --disable-libvpx
$ make
$ make install

按照这样安装会提示报错

**Comment by typefo** [comment]
目前看来问题似乎比较复杂，你可以联系我邮箱帮你远程调试 typefo@qq.com
